redirects:
    doracle: ./use-cases/iexec-doracle.md
    intro: ./README.md
    poco: ./key-concepts/proof-of-contribution.md
    pocosrc/poco-protocol: ./key-concepts/proof-of-contribution.md
    release: ./README.md # TODO
    stackdescription: ./README.md # TODO
    tee: ./for-developers/confidential-computing.md
    wallet: ./README.md # TODO
    worker: ./for-workers.md
